name: YinwuChat
main: org.lintx.plugins.yinwuchat.bukkit.YinwuChat
version: 1.3.0
author: LinTx
api-version: "1.13"
commands:
  msg:
    aliases:
      - tell
      - t
      - m
    description: Send a private message
    usage: /<command>