name: ${artifactId}
main: org.lintx.plugins.yinwuchat.bukkit.YinwuChat
version: ${version}
author: LinTx
api-version: "1.13"
depend: []
softdepend: [ConfigureCore, QuickShop]
commands:
  msg:
    aliases:
      - tell
      - t
      - m
    description: Send a private message
    usage: /<command>
  yinwuchat-bukkit:
    description: yinwuchat-bukkit command
    usage: /<command>
permissions:
  yinwuchat:
    children:
      reload:
        default: op